/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const Time = IDL.Int;
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const BlogPost = IDL.Record({
  'id' : IDL.Text,
  'title' : IDL.Text,
  'content' : IDL.Text,
  'isPublished' : IDL.Bool,
  'publishDate' : Time,
  'coverImage' : IDL.Opt(ExternalBlob),
});
export const Booking = IDL.Record({
  'id' : IDL.Text,
  'paymentStatus' : IDL.Text,
  'endDate' : Time,
  'carId' : IDL.Text,
  'userId' : IDL.Principal,
  'createdAt' : Time,
  'promoCode' : IDL.Opt(IDL.Text),
  'updatedAt' : Time,
  'bookingStatus' : IDL.Text,
  'currency' : IDL.Text,
  'addOns' : IDL.Vec(IDL.Text),
  'totalPrice' : IDL.Float64,
  'startDate' : Time,
});
export const Car = IDL.Record({
  'id' : IDL.Text,
  'featureTags' : IDL.Vec(IDL.Text),
  'model' : IDL.Text,
  'dailyRate' : IDL.Float64,
  'make' : IDL.Text,
  'year' : IDL.Nat,
  'seatCount' : IDL.Nat,
  'isAvailable' : IDL.Bool,
  'description' : IDL.Text,
  'transmission' : IDL.Text,
  'fuelType' : IDL.Text,
  'category' : IDL.Text,
  'location' : IDL.Text,
  'images' : IDL.Vec(ExternalBlob),
});
export const PromoCode = IDL.Record({
  'discountValue' : IDL.Float64,
  'expiryDate' : Time,
  'code' : IDL.Text,
  'discountType' : IDL.Text,
  'isActive' : IDL.Bool,
  'usageLimit' : IDL.Opt(IDL.Nat),
});
export const Review = IDL.Record({
  'id' : IDL.Text,
  'carId' : IDL.Text,
  'userId' : IDL.Principal,
  'createdAt' : Time,
  'reviewText' : IDL.Text,
  'rating' : IDL.Nat,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const ShoppingItem = IDL.Record({
  'productName' : IDL.Text,
  'currency' : IDL.Text,
  'quantity' : IDL.Nat,
  'priceInCents' : IDL.Nat,
  'productDescription' : IDL.Text,
});
export const UserProfile = IDL.Record({
  'preferredLanguage' : IDL.Text,
  'preferredCurrency' : IDL.Text,
  'name' : IDL.Text,
  'email' : IDL.Text,
  'phone' : IDL.Text,
});
export const Notification = IDL.Record({
  'id' : IDL.Text,
  'userId' : IDL.Principal,
  'notificationType' : IDL.Text,
  'createdAt' : Time,
  'isRead' : IDL.Bool,
  'message' : IDL.Text,
});
export const StripeSessionStatus = IDL.Variant({
  'completed' : IDL.Record({
    'userPrincipal' : IDL.Opt(IDL.Text),
    'response' : IDL.Text,
  }),
  'failed' : IDL.Record({ 'error' : IDL.Text }),
});
export const Subscriber = IDL.Record({
  'subscribedAt' : Time,
  'name' : IDL.Text,
  'email' : IDL.Text,
});
export const StripeConfiguration = IDL.Record({
  'allowedCountries' : IDL.Vec(IDL.Text),
  'secretKey' : IDL.Text,
});
export const http_header = IDL.Record({
  'value' : IDL.Text,
  'name' : IDL.Text,
});
export const http_request_result = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});
export const TransformationInput = IDL.Record({
  'context' : IDL.Vec(IDL.Nat8),
  'response' : http_request_result,
});
export const TransformationOutput = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addBlogPost' : IDL.Func([BlogPost], [], []),
  'addBooking' : IDL.Func([Booking], [], []),
  'addCar' : IDL.Func([Car], [], []),
  'addPromoCode' : IDL.Func([PromoCode], [], []),
  'addReview' : IDL.Func([Review], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createCheckoutSession' : IDL.Func(
      [IDL.Vec(ShoppingItem), IDL.Text, IDL.Text],
      [IDL.Text],
      [],
    ),
  'deleteBlogPost' : IDL.Func([IDL.Text], [], []),
  'deleteCar' : IDL.Func([IDL.Text], [], []),
  'deleteReview' : IDL.Func([IDL.Text], [], []),
  'getAllUserProfiles' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Principal, UserProfile))],
      ['query'],
    ),
  'getBlogPost' : IDL.Func([IDL.Text], [BlogPost], ['query']),
  'getBlogPosts' : IDL.Func([], [IDL.Vec(BlogPost)], ['query']),
  'getBookings' : IDL.Func([], [IDL.Vec(Booking)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCar' : IDL.Func([IDL.Text], [Car], ['query']),
  'getCars' : IDL.Func([], [IDL.Vec(Car)], ['query']),
  'getNotifications' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(Notification)],
      ['query'],
    ),
  'getPromoCodes' : IDL.Func([], [IDL.Vec(PromoCode)], ['query']),
  'getReviewsForCar' : IDL.Func([IDL.Text], [IDL.Vec(Review)], ['query']),
  'getStripeSessionStatus' : IDL.Func([IDL.Text], [StripeSessionStatus], []),
  'getSubscribers' : IDL.Func([], [IDL.Vec(Subscriber)], ['query']),
  'getUserBookings' : IDL.Func([IDL.Principal], [IDL.Vec(Booking)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isStripeConfigured' : IDL.Func([], [IDL.Bool], ['query']),
  'markNotificationAsRead' : IDL.Func([IDL.Principal, IDL.Text], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'setStripeConfiguration' : IDL.Func([StripeConfiguration], [], []),
  'subscribeToNewsletter' : IDL.Func([Subscriber], [], []),
  'transform' : IDL.Func(
      [TransformationInput],
      [TransformationOutput],
      ['query'],
    ),
  'updateBlogPost' : IDL.Func([IDL.Text, BlogPost], [], []),
  'updateBookingStatus' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'updateCar' : IDL.Func([IDL.Text, Car], [], []),
  'updatePromoCode' : IDL.Func([IDL.Text, PromoCode], [], []),
  'validatePromoCode' : IDL.Func([IDL.Text], [PromoCode], ['query']),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const Time = IDL.Int;
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const BlogPost = IDL.Record({
    'id' : IDL.Text,
    'title' : IDL.Text,
    'content' : IDL.Text,
    'isPublished' : IDL.Bool,
    'publishDate' : Time,
    'coverImage' : IDL.Opt(ExternalBlob),
  });
  const Booking = IDL.Record({
    'id' : IDL.Text,
    'paymentStatus' : IDL.Text,
    'endDate' : Time,
    'carId' : IDL.Text,
    'userId' : IDL.Principal,
    'createdAt' : Time,
    'promoCode' : IDL.Opt(IDL.Text),
    'updatedAt' : Time,
    'bookingStatus' : IDL.Text,
    'currency' : IDL.Text,
    'addOns' : IDL.Vec(IDL.Text),
    'totalPrice' : IDL.Float64,
    'startDate' : Time,
  });
  const Car = IDL.Record({
    'id' : IDL.Text,
    'featureTags' : IDL.Vec(IDL.Text),
    'model' : IDL.Text,
    'dailyRate' : IDL.Float64,
    'make' : IDL.Text,
    'year' : IDL.Nat,
    'seatCount' : IDL.Nat,
    'isAvailable' : IDL.Bool,
    'description' : IDL.Text,
    'transmission' : IDL.Text,
    'fuelType' : IDL.Text,
    'category' : IDL.Text,
    'location' : IDL.Text,
    'images' : IDL.Vec(ExternalBlob),
  });
  const PromoCode = IDL.Record({
    'discountValue' : IDL.Float64,
    'expiryDate' : Time,
    'code' : IDL.Text,
    'discountType' : IDL.Text,
    'isActive' : IDL.Bool,
    'usageLimit' : IDL.Opt(IDL.Nat),
  });
  const Review = IDL.Record({
    'id' : IDL.Text,
    'carId' : IDL.Text,
    'userId' : IDL.Principal,
    'createdAt' : Time,
    'reviewText' : IDL.Text,
    'rating' : IDL.Nat,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const ShoppingItem = IDL.Record({
    'productName' : IDL.Text,
    'currency' : IDL.Text,
    'quantity' : IDL.Nat,
    'priceInCents' : IDL.Nat,
    'productDescription' : IDL.Text,
  });
  const UserProfile = IDL.Record({
    'preferredLanguage' : IDL.Text,
    'preferredCurrency' : IDL.Text,
    'name' : IDL.Text,
    'email' : IDL.Text,
    'phone' : IDL.Text,
  });
  const Notification = IDL.Record({
    'id' : IDL.Text,
    'userId' : IDL.Principal,
    'notificationType' : IDL.Text,
    'createdAt' : Time,
    'isRead' : IDL.Bool,
    'message' : IDL.Text,
  });
  const StripeSessionStatus = IDL.Variant({
    'completed' : IDL.Record({
      'userPrincipal' : IDL.Opt(IDL.Text),
      'response' : IDL.Text,
    }),
    'failed' : IDL.Record({ 'error' : IDL.Text }),
  });
  const Subscriber = IDL.Record({
    'subscribedAt' : Time,
    'name' : IDL.Text,
    'email' : IDL.Text,
  });
  const StripeConfiguration = IDL.Record({
    'allowedCountries' : IDL.Vec(IDL.Text),
    'secretKey' : IDL.Text,
  });
  const http_header = IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text });
  const http_request_result = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  const TransformationInput = IDL.Record({
    'context' : IDL.Vec(IDL.Nat8),
    'response' : http_request_result,
  });
  const TransformationOutput = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addBlogPost' : IDL.Func([BlogPost], [], []),
    'addBooking' : IDL.Func([Booking], [], []),
    'addCar' : IDL.Func([Car], [], []),
    'addPromoCode' : IDL.Func([PromoCode], [], []),
    'addReview' : IDL.Func([Review], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createCheckoutSession' : IDL.Func(
        [IDL.Vec(ShoppingItem), IDL.Text, IDL.Text],
        [IDL.Text],
        [],
      ),
    'deleteBlogPost' : IDL.Func([IDL.Text], [], []),
    'deleteCar' : IDL.Func([IDL.Text], [], []),
    'deleteReview' : IDL.Func([IDL.Text], [], []),
    'getAllUserProfiles' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Principal, UserProfile))],
        ['query'],
      ),
    'getBlogPost' : IDL.Func([IDL.Text], [BlogPost], ['query']),
    'getBlogPosts' : IDL.Func([], [IDL.Vec(BlogPost)], ['query']),
    'getBookings' : IDL.Func([], [IDL.Vec(Booking)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCar' : IDL.Func([IDL.Text], [Car], ['query']),
    'getCars' : IDL.Func([], [IDL.Vec(Car)], ['query']),
    'getNotifications' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(Notification)],
        ['query'],
      ),
    'getPromoCodes' : IDL.Func([], [IDL.Vec(PromoCode)], ['query']),
    'getReviewsForCar' : IDL.Func([IDL.Text], [IDL.Vec(Review)], ['query']),
    'getStripeSessionStatus' : IDL.Func([IDL.Text], [StripeSessionStatus], []),
    'getSubscribers' : IDL.Func([], [IDL.Vec(Subscriber)], ['query']),
    'getUserBookings' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(Booking)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isStripeConfigured' : IDL.Func([], [IDL.Bool], ['query']),
    'markNotificationAsRead' : IDL.Func([IDL.Principal, IDL.Text], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'setStripeConfiguration' : IDL.Func([StripeConfiguration], [], []),
    'subscribeToNewsletter' : IDL.Func([Subscriber], [], []),
    'transform' : IDL.Func(
        [TransformationInput],
        [TransformationOutput],
        ['query'],
      ),
    'updateBlogPost' : IDL.Func([IDL.Text, BlogPost], [], []),
    'updateBookingStatus' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'updateCar' : IDL.Func([IDL.Text, Car], [], []),
    'updatePromoCode' : IDL.Func([IDL.Text, PromoCode], [], []),
    'validatePromoCode' : IDL.Func([IDL.Text], [PromoCode], ['query']),
  });
};

export const init = ({ IDL }) => { return []; };