/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface BlogPost {
  'id' : string,
  'title' : string,
  'content' : string,
  'isPublished' : boolean,
  'publishDate' : Time,
  'coverImage' : [] | [ExternalBlob],
}
export interface Booking {
  'id' : string,
  'paymentStatus' : string,
  'endDate' : Time,
  'carId' : string,
  'userId' : Principal,
  'createdAt' : Time,
  'promoCode' : [] | [string],
  'updatedAt' : Time,
  'bookingStatus' : string,
  'currency' : string,
  'addOns' : Array<string>,
  'totalPrice' : number,
  'startDate' : Time,
}
export interface Car {
  'id' : string,
  'featureTags' : Array<string>,
  'model' : string,
  'dailyRate' : number,
  'make' : string,
  'year' : bigint,
  'seatCount' : bigint,
  'isAvailable' : boolean,
  'description' : string,
  'transmission' : string,
  'fuelType' : string,
  'category' : string,
  'location' : string,
  'images' : Array<ExternalBlob>,
}
export type ExternalBlob = Uint8Array;
export interface Notification {
  'id' : string,
  'userId' : Principal,
  'notificationType' : string,
  'createdAt' : Time,
  'isRead' : boolean,
  'message' : string,
}
export interface PromoCode {
  'discountValue' : number,
  'expiryDate' : Time,
  'code' : string,
  'discountType' : string,
  'isActive' : boolean,
  'usageLimit' : [] | [bigint],
}
export interface Review {
  'id' : string,
  'carId' : string,
  'userId' : Principal,
  'createdAt' : Time,
  'reviewText' : string,
  'rating' : bigint,
}
export interface ShoppingItem {
  'productName' : string,
  'currency' : string,
  'quantity' : bigint,
  'priceInCents' : bigint,
  'productDescription' : string,
}
export interface StripeConfiguration {
  'allowedCountries' : Array<string>,
  'secretKey' : string,
}
export type StripeSessionStatus = {
    'completed' : { 'userPrincipal' : [] | [string], 'response' : string }
  } |
  { 'failed' : { 'error' : string } };
export interface Subscriber {
  'subscribedAt' : Time,
  'name' : string,
  'email' : string,
}
export type Time = bigint;
export interface TransformationInput {
  'context' : Uint8Array,
  'response' : http_request_result,
}
export interface TransformationOutput {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface UserProfile {
  'preferredLanguage' : string,
  'preferredCurrency' : string,
  'name' : string,
  'email' : string,
  'phone' : string,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface http_header { 'value' : string, 'name' : string }
export interface http_request_result {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  /**
   * / Admin only: create a blog post.
   */
  'addBlogPost' : ActorMethod<[BlogPost], undefined>,
  /**
   * / Authenticated users only: create a booking.
   * / The booking's userId must match the caller.
   */
  'addBooking' : ActorMethod<[Booking], undefined>,
  /**
   * / Admin only: create a car record.
   */
  'addCar' : ActorMethod<[Car], undefined>,
  /**
   * / Admin only: create a promo code.
   */
  'addPromoCode' : ActorMethod<[PromoCode], undefined>,
  /**
   * / Authenticated users only: submit a review.
   * / The review's userId must match the caller.
   */
  'addReview' : ActorMethod<[Review], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createCheckoutSession' : ActorMethod<
    [Array<ShoppingItem>, string, string],
    string
  >,
  /**
   * / Admin only: delete a blog post.
   */
  'deleteBlogPost' : ActorMethod<[string], undefined>,
  /**
   * / Admin only: delete a car record.
   */
  'deleteCar' : ActorMethod<[string], undefined>,
  /**
   * / Admin only: delete an inappropriate review.
   */
  'deleteReview' : ActorMethod<[string], undefined>,
  /**
   * / Admin only: list all user profiles.
   */
  'getAllUserProfiles' : ActorMethod<[], Array<[Principal, UserProfile]>>,
  /**
   * / Public: get a single blog post (published); admin can also see drafts.
   */
  'getBlogPost' : ActorMethod<[string], BlogPost>,
  /**
   * / Public: list all published blog posts.
   */
  'getBlogPosts' : ActorMethod<[], Array<BlogPost>>,
  /**
   * / Admin only: view all bookings.
   */
  'getBookings' : ActorMethod<[], Array<Booking>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  /**
   * / Public: anyone can view a single car.
   */
  'getCar' : ActorMethod<[string], Car>,
  /**
   * / Public: anyone can browse the car catalogue.
   */
  'getCars' : ActorMethod<[], Array<Car>>,
  /**
   * / Authenticated user: view own notifications; admin: view any user's notifications.
   */
  'getNotifications' : ActorMethod<[Principal], Array<Notification>>,
  /**
   * / Admin only: list all promo codes.
   */
  'getPromoCodes' : ActorMethod<[], Array<PromoCode>>,
  /**
   * / Public: anyone can read reviews for a car.
   */
  'getReviewsForCar' : ActorMethod<[string], Array<Review>>,
  'getStripeSessionStatus' : ActorMethod<[string], StripeSessionStatus>,
  /**
   * / Admin only: view all newsletter subscribers.
   */
  'getSubscribers' : ActorMethod<[], Array<Subscriber>>,
  /**
   * / Authenticated user: view own bookings; admin: view any user's bookings.
   */
  'getUserBookings' : ActorMethod<[Principal], Array<Booking>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'isStripeConfigured' : ActorMethod<[], boolean>,
  /**
   * / Authenticated user: mark own notification as read; admin: mark any.
   */
  'markNotificationAsRead' : ActorMethod<[Principal, string], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'setStripeConfiguration' : ActorMethod<[StripeConfiguration], undefined>,
  /**
   * / Public: anyone can subscribe to the newsletter.
   */
  'subscribeToNewsletter' : ActorMethod<[Subscriber], undefined>,
  'transform' : ActorMethod<[TransformationInput], TransformationOutput>,
  /**
   * / Admin only: update a blog post.
   */
  'updateBlogPost' : ActorMethod<[string, BlogPost], undefined>,
  /**
   * / Admin only: update booking status and notify the user.
   */
  'updateBookingStatus' : ActorMethod<[string, string], undefined>,
  /**
   * / Admin only: update a car record.
   */
  'updateCar' : ActorMethod<[string, Car], undefined>,
  /**
   * / Admin only: update a promo code.
   */
  'updatePromoCode' : ActorMethod<[string, PromoCode], undefined>,
  /**
   * / Authenticated users: validate and retrieve a promo code at checkout.
   */
  'validatePromoCode' : ActorMethod<[string], PromoCode>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];